RENAME TABLE movies TO medias;

CREATE TABLE IF NOT EXISTS comments
(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	media_id INT NOT NULL,
	user_id INT NOT NULL,
	comment VARCHAR(255) NOT NULL,
	creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT fk_media_id FOREIGN KEY (media_id) REFERENCES medias(id),
	CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

ALTER TABLE medias DROP hash;
ALTER TABLE medias DROP creation_date;


ALTER TABLE medias ADD imdb_id VARCHAR(255) NOT NULL;

CREATE TABLE IF NOT EXISTS torrents
(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	hash VARCHAR(255) NOT NULL,
	creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);