ALTER TABLE torrents ADD extension VARCHAR(20);

DROP TABLE torrents;

CREATE TABLE IF NOT EXISTS torrents
(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	hash VARCHAR(255) NOT NULL,
	torrent_name VARCHAR(255) NOT NULL,
	creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	extension VARCHAR(20) NOT NULL
);